version: "3"

services:
  webserver:
    build:
      context: ./docker/php
    container_name: "${PROJECT_NAME}-php"
    ports:
      - "38:80"
    depends_on:
      - redis
    volumes:
      - ${DOCUMENT_ROOT-./}:/var/www/:rw
      - ${PHP_INI-./docker/php/php.ini}:/usr/local/etc/php/php.ini
      - ${XDEBUG_LOG_DIR-./logs/xdebug}:/var/log/xdebug
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      HOST_MACHINE_MYSQL_PORT: ${HOST_MACHINE_MYSQL_PORT}
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=${XDEBUG_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - learn-slim
  redis:
    build:
      context: ./docker/redis
    container_name: "${PROJECT_NAME}-redis"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      - learn-slim
volumes:
  redis:
    driver: local

networks:
  learn-slim:
    driver: bridge