<?php

namespace Slavytuch\LearnSlim\Handlers;

use Slim\Handlers\ErrorHandler;

class MyErrorHandler extends ErrorHandler
{
    protected function logError(string $error): void
    {
        parent::logError($error); // TODO: Change the autogenerated stub
    }
}